### ISSUE TITLE
Linear model assumptions

### ISSUE THREAD

**Issue by jlopezper** [trainindata/deploying-machine-learning-models#237]
In the "Machine Learning Pipeline: Feature Engineering" video (Section 2) you mention that one of the assumptions of linear models is that variables should be normally distributed and this is not correct. This assumption applies to the errors and it affects to the calculation of confidence intervals.

Thanks for the course!

**Comment by shabraatgit** [comment]
@jlopezper well, I beg to differ, linear model does work better with normally distributed data. The lecture notes refer to assumptions to optimally use a linear model regressor and classifier.

**Comment by jlopezper** [comment]
Could you share any reference about that?

**Comment by Amaury-Barra** [comment]
Greene

**Comment by solegalli** [comment]
@jlopezper you are right, we fixed this several months ago in the course. @cbr-repo is also right, but I am not aware of any references that document this, I think it is mostly practitioner's experience. 

I will close this issue now. Thank you for your engagement :)
