### ISSUE TITLE
pytest error

### ISSUE THREAD

**Issue by anandsm7** [trainindata/deploying-machine-learning-models#96]
I am facing this error while executing the test script

=================================== ERRORS ====================================
______ ERROR collecting packages/regression_model/tests/test_predict.py _______
ImportError while importing test module 'D:\deploy\deploying-machine-learning-models\packages\regression_model\tests\test_predict.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
packages\regression_model\tests\test_predict.py:3: in <module>
    from regression_model.predict import make_prediction
packages\regression_model\regression_model\predict.py:9: in <module>
    _price_pipe = load_pipeline(file_name=pipeline_file_name)
packages\regression_model\regression_model\processing\data_management.py:29: in load_pipeline
    saved_pipeline = joblib.load(filename=file_path)
env\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py:598: in load
    obj = _unpickle(fobj, filename, mmap_mode)
env\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py:526: in _unpickle
    obj = unpickler.load()
C:\Users\user\Anaconda3\lib\pickle.py:1085: in load
    dispatch[key[0]](self)
C:\Users\user\Anaconda3\lib\pickle.py:1373: in load_global
    klass = self.find_class(module, name)
C:\Users\user\Anaconda3\lib\pickle.py:1423: in find_class
    __import__(module, level=0)
E   ModuleNotFoundError: No module named 'preprocessors'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 1 error in 4.65 seconds ===========================

**Comment by rkarr5** [comment]
I am also getting the same error. How did you resolved it
